services:
  postgres:
    image:  postgres:16
    container_name: ecommerce-db-dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce_shop
    ports:
      - "5433:5432"
    volumes:
      - ecommerce_db_dev_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:latest
    container_name: ecommerce-localstack-dev
    environment:
      - SERVICES=s3,sqs
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"  # LocalStack Gateway
    volumes:
      - ecommerce_localstack_dev_data:/var/lib/localstack

volumes:
  ecommerce_db_dev_data:
  ecommerce_localstack_dev_data:
